/** @jsxImportSource @emotion/react */
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Layout } from "../components";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Layout home={true}>
        <Head>
          <title>Aimee&lsquo;s Blog</title>
          {/* <meta name="description" content="Generated by create next app" /> */}
          {/* <link rel="icon" href="/favicon.ico" /> */}
        </Head>
      </Layout>
    </div>
  );
}
